### ISSUE TITLE
Bugs/Formatting Issues

### ISSUE THREAD

**Issue by norangeflame** [Crazypersonalph/HyperSEQTA#40] opened 2023-06-27 10:38 UTC
Just making a list of small bugs and formatting glitches that I've found. Will be able to help out in around a week once school is done.
Pictures attached with explanation. I may add to or remove things from this list as they are discovered or fixed. 

***List:***
- [x] Some text on specific pages does not change colour to contrast the background. Pages: Documents; Dashboard.
- [x] Unintended theme tag. (SEQTA specific, not a HTML tag, more info below).
- [x] DM colour and formatting. (Specifically with dark mode, only happens with some DMs). <-- @Crazypersonalph I remember us attempting to fix this, not sure if we did but the issue is still there from testing with the latest Dev branch.
- [x] Home page does not show Filters for Notices.
- [x] #52
- [x] Bug with "What's New" page. This bug is not present in Nulkem's last update (2.0.8), and I have strong suspicion it has to do with the stringToHTML function that we have had previous troubles with.

***More info:***
- **Contrast issue**
![dimBG_increaseContrastFilesize_changeColourHovered](https://github.com/Crazypersonalph/betterseqta/assets/106525819/b0ae0225-d3ab-4176-9924-198833e860d7)
Hovering over a document makes it bright white. This might be an issue with dark/light mode (white hover colour for light mode isn't changed to a dark grey hover colour for dark mode). 
The file size column is extremely hard to read (not changing to contrast the background colour).
The colours behind document descriptions are very bright, and they don't change colour when changing background colour (always green and pink). 
The document title also stays blue and doesn't change if background is changed. On black it is readable, on other colours it might not be.

- **Contrast/readability issue**
![increaseContrastAndReadability](https://github.com/Crazypersonalph/betterseqta/assets/106525819/47cdbfa2-ff55-4c20-9ce1-f1fe6a32bd93)
Text is hard to read (not changing from original colour when switching to dark mode).

- **Theme tag not handled on Home page notices**
![unintendedThemeTag](https://github.com/Crazypersonalph/betterseqta/assets/106525819/2f64d7b6-ebde-4e9f-a1ab-392089557eae)
Some notices have a [[theme:themename]] tag. Notices will only have this if they were created with a theme, and the tag only shows up on the Home page (not the Notices page). On the normal Notices page, the theme is displayed correctly (pictured below). This tag is most likely a SEQTA-specific tag.
Normal theme handling:
![normalThemeTagBehaviour](https://github.com/Crazypersonalph/betterseqta/assets/106525819/3841ba26-baa6-4ccc-98b3-f520aa32d031)

- **Home page doesn't show Filters for Notices**
Filters on the notices page:
![image](https://github.com/Crazypersonalph/betterseqta/assets/106525819/b0480ec8-e853-4b74-afa0-cfc74a886459)
Notices on home page don't have an option for filters; instead they display everything.
Found by @proJM-Coding

- **Bug with the display of the currently selected tab on the main side menu**
![gif](https://github.com/Crazypersonalph/betterseqta/assets/106525819/323e1540-3d62-480d-881c-c547eb08cb14)
Pressing the "Pen" icon to modify menu layout, and then clicking elsewhere on the screen to turn of the menu editing function breaks the white "selected" indicator on each item. See attached GIF (orange circles indicate mouse clicks).

- **Bug with the "What's New" page that displays after each update or after a new install of the BetterSEQTA extension**
![image](https://github.com/Crazypersonalph/betterseqta/assets/106525819/7d85651a-1bf7-4e5e-aa88-75cd59cdf5b9)
Above is the What's New page for version 2.0.8, the latest official version before the project was abandoned.
It contains three images (one not pictured) that are packed with the extension.
Below is the What's New page for version 2.0.9:
![missingImages_stringToHTML-Bug](https://github.com/Crazypersonalph/betterseqta/assets/106525819/c55f3e73-35ab-4c06-aeb0-d918922ee195)
It is missing these images. I am fairly sure this has to do with the stringToHTML function, which is used to create the HTML for the popup page. Below is a snippet, from the function "OpenWhatsNewPopup()" on line 122 of SEQTA.js (latest dev branch):
![image](https://github.com/Crazypersonalph/betterseqta/assets/106525819/59a77aea-76d8-419a-9b59-ed416a14b06c)
My reason for suspecting the stringToHTML function is because it is a function we worked on/modified previously, and it works fine in Nulkem's version.

As I said, I can try help with fixing these once school is over.

**Comment by norangeflame** [comment] 2023-06-27 10:40
And just as I send that, I find a bug.

**Comment by Crazypersonalph** [comment] 2023-06-28 06:55
So with the problem with the document description column, I believe the colours are assigned by your school for each type of document, so I will aim to change the alpha, rather than the colour as a whole.

**Comment by ghost** [comment] 2023-08-18 01:20
I have found one more formatting issue, while I am in dark mode the calendar stays in light mode.
![image](https://github.com/Crazypersonalph/betterseqta/assets/81658610/b0b78d9c-ea28-4185-a139-b0d42f9c511f)

**Comment by proJM-Coding** [comment] 2023-08-24 09:37
Another found, in the home tab for some reason the text doesn't show but in the notices it does. Note there is no formating for the notice but it doesn't show for some reason.

![image](https://github.com/Crazypersonalph/betterseqta/assets/81658610/5198e3d3-ec27-4723-83df-38f5fae587cb)

**Comment by ghost** [comment] 2023-08-24 09:38
Another found, in the home tab for some reason the text doesn't show but in the notices it does. Note there is no formating for the notice but it doesn't show for some reason.

![Screenshot 2023-08-24 19 05 12](https://github.com/Crazypersonalph/betterseqta/assets/81658610/2336438c-3712-49d7-ace7-37708b9eabb6)

**Comment by ghost** [comment] 2023-09-18 02:53
This is a bug my friend found, you can see that it says submitted 3 times. This isn't even because there are 3 files submitted though because there are 2 files. Also the contrast doesn't work well

![Screenshot 2023-09-18 10 46 16 AM](https://github.com/Crazypersonalph/betterseqta/assets/81658610/384e6284-5a54-4dc6-a309-45c515fde254)
![Screenshot 2023-09-18 10 46 41 AM](https://github.com/Crazypersonalph/betterseqta/assets/81658610/74e6d57b-56a9-4bc2-a5a3-1226c813ef3c)

**Comment by Crazypersonalph** [comment] 2023-11-23 08:08
Fixed DM formatting issue in a86ac32 on dev branch

**Comment by ghost** [comment] 2023-11-23 08:09
Thank you

**Comment by Crazypersonalph** [comment] 2023-11-23 08:27
@norangeflame Do you still have this issue? I can't seem to reproduce it.

**Comment by Crazypersonalph** [comment] 2023-11-25 07:44
Theme tags fixed in 607d55b

**Closed as completed by Crazypersonalph** 2023-11-25 07:44 UTC
Labels: bug, enhancement, UI/UX
